name = "SupplyChainModels"
uuid = "562ae68e-5bc4-4bde-9b2c-0154754d073e"
authors = ["Jorbnc <67754592+Jorbnc@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
DecFP = "55939f99-70c6-5e9b-8bb0-5071ed7d61fd"

[compat]
julia = "1"
DecFP = "1.2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
